In [144]:
import numpy as np
import numpy
import pandas as pd
from pandas import read_csv
import warnings
warnings.filterwarnings('ignore')

# SP 2022

In [44]:
# load data
#SP_20_22 = read_csv('filtered_df_SP_final.csv', delimiter=",", low_memory=False, keep_default_na=False)

In [45]:
#SP_22 = SP_20_22[SP_20_22['year'] == 2022]

In [46]:
#tirar coluna 'Unnamed'
#SP_22 = SP_22.drop(SP_22.columns[0], axis=1)

In [1]:
#SP_22

In [2]:
#SP_22.to_csv("SP_22.csv")

# SP 2020

In [49]:
SP_20 = SP_20_22[SP_20_22['year'] == 2020]

In [50]:
SP_20 = SP_20.drop(SP_20.columns[0], axis=1)

In [51]:
#SP_20

,SG_UF_NOT,month,year,DESC_RESP,DIARREIA,DISPNEIA,DOR_ABD,FADIGA,FEBRE,GARGANTA,PERD_OLFT,PERD_PALA,SATURACAO,TOSSE,VOMITO,CLASSI_FIN
3,SP,1,2020,1,2,1,0,0,1,2,0,0,1,1,2,0
4,SP,1,2020,1,2,2,0,0,1,1,0,0,1,1,2,0
5,SP,1,2020,1,2,1,0,0,1,2,0,0,2,1,2,0
6,SP,1,2020,2,2,1,0,0,1,2,0,0,2,1,2,0
7,SP,1,2020,1,2,1,0,0,1,2,0,0,1,2,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302071,SP,12,2020,1,1,2,2,2,2,2,2,1,2,1,1,1
302072,SP,12,2020,2,2,2,2,2,1,2,2,2,2,1,2,1
302073,SP,12,2020,1,2,1,2,1,2,2,2,2,1,2,2,1
302074,SP,12,2020,1,2,1,2,1,1,1,2,2,1,1,2,1
302075,SP,12,2020,2,2,2,1,2,1,2,2,2,1,1,2,1

In [52]:
SP_20.to_csv("SP_20.csv")

# SP 2021

In [53]:
#SP_21 = SP_20_22[SP_20_22['year'] == 2021]

In [54]:
#SP_21 = SP_21.drop(SP_21.columns[0], axis=1)

In [3]:
#SP_21

In [56]:
#SP_21.to_csv("SP_21.csv")